meta_name: "iNeed"
meta_title: iNeed - Community Grocery App"
meta_description: "Designed to facilitate grocery shopping in your neighborhood"
meta_image: "friendship.png" # should exist in `app/assets/images/`
